version: "3.0"

services:
  api:
    container_name: "autonomous-api"
    volumes:
      - .:/var/www/
    build: .
    ports:
      - 5020:8080
    env_file:
      - .env
    networks:
      - koboriakira-docker-network

networks:
  koboriakira-docker-network:
    driver: bridge
    external: true
